### ISSUE TITLE
Terraform plan errors

### ISSUE THREAD

**Issue by GodAtum360** [okami101/terraform-hcloud-k3s#2]
Using your github files without changes, I get the following errors:

```
Error: Duplicate output definition
│ 
│   on output.tf line 28:
│   28: output "ssh_config" {
│ 
│ An output named "ssh_config" was already defined at kube.tf:204,1-20. Output names must be unique within a module.
```

```
│ Error: Duplicate required providers configuration
│ 
│   on versions.tf line 2, in terraform:
│    2:   required_providers {
│ 
│ A module may have only one required providers configuration. The required providers were previously configured at kube.tf:2,3-21.
```

**Comment by adr1enbe4udou1n** [comment]
Bad usage from your side 😊

Please check the readme carefully :

1. Copy [this kube config example](kube.tf.example) **into a new empty directory** and rename it `kube.tf`.
2. Execute `terraform init` in order to install the required module
3. Replace all variables according your own needs.
4. Finally, use `terraform apply` to check the plan and initiate the cluster setup.

So don't clone this repo, simply create a new empty directory with only the kube.tf file copied from the exemple.

Same applies to https://github.com/okami101/terraform-hcloud-swarm
